### ISSUE TITLE
Error in Setting destination

### ISSUE THREAD

**Issue by udhay111** [FreeCAD/FreeCAD-symbols#4]
# Error code <class 'SyntaxError'>
Whenever i tried to run the Macro i get the following error code
```21:33:01  <class 'SyntaxError'>: ('invalid syntax', ('C:/Users/Admin/AppData/Roaming/FreeCAD/Macro/SymbolsLibrary.FCMacro', 157, 11, '    print "Symbols library path ", LIBRARYPATH, "not found."\n'))```
 Please elaborate me where to change the code so that location of symbols is found

**Comment by luzpaz** [comment]
You're missing your full [About](https://wiki.freecad.org/About) info. Also can you check on the forum to see if anyone can reproduce? (http://forum.freecadweb.org/viewtopic.php?f=9&t=10641)

**Comment by yorikvanhavre** [comment]
This macro had never been ported to py3 :)
